language: ruby
rvm: 2.1

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true  # speeds up installation of html-proofer

install:
  # Skip document generation to speed up install
  - gem install jekyll --no-document
  - gem install html-proofer --no-document

script:
  - jekyll build
  - htmlproof ./_site
