language: ruby
rvm: 2.7.4

cache: bundler

addons:
  apt:
    packages:
    - libcurl4-openssl-dev  # required to avoid SSL errors

script:
  - bundle exec jekyll build && bundle exec htmlproofer ./_site
