language: ruby
rvm: 2.1

sudo: false
cache: bundler

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true  # speeds up installation of html-proofer

script:
  - bundle exec jekyll build && bundle exec htmlproof ./_site
