### GENERAL SETTINGS ###

# Site settings
title: APEL
# Default subheading if not defined in a page's index.md
subheading: APEL client and server source code
# The description will appear in the document head meta (for Google search results) and in the feed.xml site description.
description: "GitHub Page for the APEL project."
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "https://apel.github.io"

safe: true

# Travis bundles gems in the vendor directory which Jekyll will fail on if it's not excluded.
exclude: [vendor]

# Build settings
markdown: kramdown
permalink: /:categories/:title/
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031" 
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.  
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"

### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: dribbble
    url:
  - title: facebook
    url:
  - title: twitter
    url: 

# Contact Details (add as many lines as necessary). Shown in footer and on Contact page.
tickets: APEL SU at https://ggus.eu/
email: apel-admins [at] stfc.ac.uk

### GENERAL DATA FOR VARIOUS LOCATIONS ###
    
# Maintainers information. Shown on About page.
maintainers:
  - name: Adrian Coveney
    url: https://github.com/tofu-rocketry
  - name: Greg Corbett
    url: https://github.com/gregcorbett
    
# Contributors information. Shown on Home and About pages.
contributors:
  - name: Alison Packer 
    url: https://github.com/alisonpacker
  - name: David Rebatto
    url: https://github.com/drebatto
  - name: Henning Perl 
    url: https://github.com/hperl
  - name: Josh Hadley
    url: https://github.com/CJoriginal
  - name: Konrad Jopek
    url: https://github.com/kjopek
  - name: konvpalto
    url: https://github.com/konvpalto
  - name: Pablo Orviz
    url: https://github.com/orviz
  - name: Pavel Demin
    url: https://github.com/pavel-demin
  - name: Stuart Pullinger
    url: https://github.com/stuartpullinger
  - name: Will Rogers
    url: https://github.com/willrogers

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "APEL is an accounting tool that collects accounting data from sites participating in the EGI and WLCG infrastructures as well as from sites belonging to other Grid organisations that are collaborating with EGI, including OSG, NorduGrid and INFN."
